export default {
  choiceLabel: 'Choice Label goes here',
  choices: [],
  correctResponse: [],
  enableImages: false,
  prompt: 'Item Stem goes here',
  lockChoiceOrder: false,
  numberedGuides: false,
  orientation: 'vertical',
  partialScoring: true,
  placementArea: false,
  removeTilesAfterPlacing: true,
  scoringType: 'auto',
  targetLabel: 'Target Label goes here',
  rationaleEnabled: true,
  feedbackEnabled: true,
  promptEnabled: true,
  teacherInstructionsEnabled: true,
  studentInstructionsEnabled: true
};
