export default {
  choiceLabel: '',
  choices: [],
  correctResponse: [],
  enableImages: false,
  prompt: 'Item Stem goes here',
  numberedGuides: false,
  orientation: 'vertical',
  partialScoring: true,
  placementArea: false,
  choiceLabelEnabled: true,
  removeTilesAfterPlacing: true,
  scoringType: 'auto',
  targetLabel: '',
  note: 'The answer shown above is the most common correct answer for this item. One or more additional correct answers are also defined, and will also be recognized as correct.',
  rationaleEnabled: true,
  feedbackEnabled: true,
  promptEnabled: true,
  teacherInstructionsEnabled: true,
  studentInstructionsEnabled: true
};
