export default {
  choiceLabel: '',
  choiceLabelEnabled: true,
  choices: [],
  correctResponse: [],
  enableImages: false,
  feedbackEnabled: false,
  numberedGuides: false,
  orientation: 'vertical',
  partialScoring: true,
  placementArea: false,
  prompt: '',
  promptEnabled: true,
  rationale: '',
  rationaleEnabled: true,
  removeTilesAfterPlacing: true,
  scoringType: 'auto',
  studentInstructionsEnabled: true,
  targetLabel: '',
  teacherInstructions: '',
  teacherInstructionsEnabled: true,
  toolbarEditorPosition: 'bottom',
};
