export default {
  feedbackEnabled: false,
  highlightChoices: false,
  maxSelections: 2,
  mode: 'sentence',
  partialScoring: false,
  prompt: '',
  promptEnabled: true,
  rationale: '',
  rationaleEnabled: true,
  scoringType: 'auto',
  studentInstructionsEnabled: true,
  teacherInstructions: '',
  teacherInstructionsEnabled: true,
  text: '',
  tokens: [],
  toolbarEditorPosition: 'bottom',
};
