export default {
  choiceMode: 'checkbox',
  choicePrefix: 'letters',
  choices: [],
  prompt: '',
  lockChoiceOrder: true,
  partialScoring: true,
  scoringType: 'auto',
  feedbackEnabled: true,
  promptEnabled: true,
  rationaleEnabled: true,
  teacherInstructionsEnabled: true,
  studentInstructionsEnabled: true,
  toolbarEditorPosition: 'bottom',
  choicesLayout: 'vertical',
  gridColumns: '2',
};
