export default {
  choiceMode: 'radio',
  enableImages: true,
  feedbackEnabled: false,
  headers: ['Column 1', 'Column 2', 'Column 3'],
  layout: 3,
  lockChoiceOrder: true,
  partialScoring: false,
  prompt: '',
  promptEnabled: true,
  rationale: '',
  rationaleEnabled: true,
  rows: [],
  scoringType: 'auto',
  studentInstructionsEnabled: true,
  teacherInstructions: '',
  teacherInstructionsEnabled: true,
  toolbarEditorPosition: 'bottom',
};
