export default {
  prompt: '',
  toolbarEditorPosition: 'bottom',
  imageUrl: '',
  shapes: {
    rectangles: [],
    polygons: [],
    circles: [],
  },
  multipleCorrect: true,
  partialScoring: false,
  dimensions: {
    height: 0,
    width: 0,
  },
  hotspotColor: 'rgba(137, 183, 244, 0.25)',
  hotspotList: ['rgba(137, 183, 244, 0.25)'],
  outlineColor: 'blue',
  outlineList: ['blue'],
  promptEnabled: true,
  rationaleEnabled: true,
  teacherInstructionsEnabled: true,
  studentInstructionsEnabled: true,
  strokeWidth: 5,
  selectedHotspotColor: 'rgba(255, 229, 67, 0.3)',
  hoverOutlineColor: 'green',
};
