export default {
  disabled: false,
  mode: 'gather',
  prompt: '',
  markup: '',
  choices: [],
  choicesPosition: 'below',
  correctResponse: {},
  duplicates: true,
  rationaleEnabled: true,
  promptEnabled: true,
  teacherInstructionsEnabled: true,
  studentInstructionsEnabled: true,
  toolbarEditorPosition: 'bottom',
};
