// !! configure src defaults models needs to have the same content as controller src defaults
export default {
  partLabels: true,
  partLabelType: 'Letters',
  partialScoring: false,
  partA: {
    choiceMode: 'radio',
    choices: [],
    choicePrefix: 'numbers',
    prompt: '',
    teacherInstructions: '',
    rationale: '',
    spellCheckEnabled:true,
    choicesLayout: 'vertical',
    disabled: false,
    rationaleEnabled: true,
    feedbackEnabled: true,
    promptEnabled: true,
    teacherInstructionsEnabled: true,
    studentInstructionsEnabled: true,
    gridColumns: '2',
  },
  partB: {
    choiceMode: 'radio',
    choices: [],
    choicePrefix: 'numbers',
    prompt: '',
    teacherInstructions: '',
    rationale: '',
    spellCheckEnabled:true,
    choicesLayout: 'vertical',
    disabled: false,
    rationaleEnabled: true,
    feedbackEnabled: true,
    promptEnabled: true,
    teacherInstructionsEnabled: true,
    studentInstructionsEnabled: true,
    gridColumns: '2',
  },
};
